config/routes.rb
Rails.application.routes.draw do
  
  root to: "tasks#index"
  resources :tasks
  
  get "signup", to: "users#new"
  resources :users, only: [:create]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
=begin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # CRUD
  get "tasks/:id" => "task#show"
  post "tasks" => "task#create"
  put "tasks/:id" => "tasks#update"
  delete "tasks/:id" => "tasks#destroy"

  # index: show の補助ページ。index はshowへの一覧ページ
  get "tasks" => "tasks#index"
  
  # new: 新規作成用のフォームページ。create を補助する。
  get "tasks/new" => "tasks#new"
  
  # edit: 更新用のフォームページ。update に転送する。
  get "tasks/:id/edit" => "tasks#edit"
=end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  include Pagy::Backend
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :show, :edit, :update]
  
  def index
    @pagy, @tasks = pagy(current_user.tasks.order(id: :desc))
  end
  
  def show
  end
  
  def new
    @task = current_user.tasks.build
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "タスクが追加されました"
      redirect_to root_url
    else
      flash.now[:danger] = "タスクが追加されませんでした"
      render :new
    end
  end
  
  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = "タスクは更新されました"
      redirect_to @task
    else
      flash.now[:danger] = "タスクは更新されませんでした"
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = "タスクは削除されました"
    redirect_to root_url
  end
  
  private
  
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |f| %>
  
  <%= f.label :status, "ステータス" %>
  <%= f.text_field :status %>
  
  <%= f.label :content, "タスク" %>
  <%= f.text_field :content %>
  
  <%= f.submit "追加" %>
<% end %>

app/views/tasks/_tasks.html.erb
<% if tasks.any? %>
  <ul>
    <% tasks.each do |task| %>
      <li>
        <p><%= link_to task.user.name, task %></p>
        <p><%= link_to task.status, task %></p>
        <p><%= link_to task.content, task %></p>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集ページ</h1>

<%= render "form", task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/index.html.erb
<% if logged_in? %>

  <p>ログイン完了ユーザ: <%= current_user.name %></p>
    
  <h1>タスク一覧</h1>
  
  <%= render "tasks", tasks: @tasks %>
  
  <%= link_to "新規タスクの追加", new_task_path %>
  <%= link_to 'ログアウト', logout_path, method: :delete %>

<% else %>

<h1>タスクリスト</h1>

<%= link_to 'サインアップ', signup_path %>
<%= link_to 'Login', login_path %>

<% end %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'layouts/error_messages', model: @task %>
<%= render "form", task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>タスクの詳細ページ</h1>

<p>ステータス: <%= @task.status %></p>
<p>タスク: <%= @task.content %></p>

<%= link_to "一覧に戻る", tasks_path %>
<%= link_to "編集する", edit_task_path(@task) %>

<% if current_user == @task.user %>
  <%= link_to "削除", @task, method: :delete, data: { confirm: "You sure?" } %>
<% end %>

app/views/users/new.html.erb
<div>
  <h1>サインアップ</h1>
</div>

<div>
    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div>
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name %>
      </div>

      <div>
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email %>
      </div>

      <div>
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password %>
      </div>

      <div>
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation %>
      </div>

      <%= f.submit '登録' %>
    <% end %>
  </div>
</div>

<p>もしくは <%= link_to 'ログイン', login_path %></p>